Update docker-compose.yml

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -116,6 +116,79 @@ services:
       # - ./container-data/kafka/kafka-data-3:/var/lib/kafka/data
       - kafka-data-3:/var/lib/kafka/data
 
+  kafka-init:
+    image: ${KAFKA_IMAGE}
+    container_name: kafka-init
+    depends_on:
+      kafka-1:
+        condition: service_healthy
+      kafka-2:
+        condition: service_healthy
+      kafka-3:
+        condition: service_healthy
+    networks:
+      - kafka-net
+    restart: "no"
+    entrypoint:
+      - /bin/bash
+      - -c
+      - |
+          set -e
+
+          BOOTSTRAP="kafka-1:9094"
+
+          echo "Kafka is healthy. Creating topics..."
+
+          # ----------------------------
+          # Core topics
+          # ----------------------------
+
+          /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka-1:9094 --create --topic pothole.raw.events.v1 \
+              --partitions 12 --replication-factor 3 \
+              --if-not-exists \
+              --config retention.ms=604800000 --config cleanup.policy=delete
+
+          /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka-1:9094 --create --topic pothole.depth.v1 \
+              --partitions 12 --replication-factor 3 \
+              --if-not-exists \
+              --config retention.ms=259200000 --config cleanup.policy=delete
+
+          /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka-1:9094 --create --topic pothole.surface.area.v1 \
+              --partitions 12 --replication-factor 3 \
+              --if-not-exists \
+              --config retention.ms=259200000 --config cleanup.policy=delete
+
+          /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka-1:9094 --create --topic pothole.severity.score.v1 \
+              --partitions 12 --replication-factor 3 \
+              --if-not-exists \
+              --config retention.ms=604800000 --config cleanup.policy=delete
+
+          # ----------------------------
+          # DLQ topics
+          # ----------------------------
+
+          /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka-1:9094 --create --topic pothole.raw.events.dlq.v1 \
+              --partitions 12 --replication-factor 3 \
+              --if-not-exists \
+              --config retention.ms=1209600000 --config cleanup.policy=delete
+
+          /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka-1:9094 --create --topic pothole.depth.dlq.v1 \
+              --partitions 12 --replication-factor 3 \
+              --if-not-exists \
+              --config retention.ms=1209600000 --config cleanup.policy=delete
+
+          /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka-1:9094 --create --topic pothole.surface.area.dlq.v1 \
+              --partitions 12 --replication-factor 3 \
+              --if-not-exists \
+              --config retention.ms=1209600000 --config cleanup.policy=delete
+
+          /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka-1:9094 --create --topic pothole.severity.score.dlq.v1 \
+              --partitions 12 --replication-factor 3 \
+              --if-not-exists \
+              --config retention.ms=1209600000 --config cleanup.policy=delete
+
+          echo "Kafka topic initialization complete."
+
   # ==========================================================
   #  KAFKA UI (Kafka management interface)
   # ==========================================================
@@ -267,16 +340,18 @@ services:
   # ==========================================================
   #  GRAFANA MONITORING DASHBOARD
   # ==========================================================
-  # grafana:
-  #   image: grafana/grafana:10.0.0
-  #   container_name: grafana
-  #   ports:
-  #     - "3000:3000"
-  #   volumes:
-  #     # - ./container-data/grafana/data:/var/lib/grafana
-  #     - grafana-data:/var/lib/grafana
-  #   networks:
-  #     - kafka-net
+  grafana:
+    image: grafana/grafana:10.0.0
+    container_name: grafana
+    ports:
+      - "3001:3000"
+    environment:
+      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=trino-datasource
+    volumes:
+      # - ./container-data/grafana/data:/var/lib/grafana
+      - grafana-data:/var/lib/grafana
+    networks:
+      - kafka-net
 
   # ==========================================================
   #  POLARIS - REST DATA CATALOG FOR ICECBERG
@@ -322,28 +397,89 @@ services:
     environment:
       - CLIENT_ID=root
       - CLIENT_SECRET=s3cr3t
-    volumes:
-      - ./container-conf/polaris/:/polaris
     entrypoint: "/bin/sh"
     command:
       - "-c"
       - >-
-        chmod +x /polaris/create-catalog.sh;
-        chmod +x /polaris/obtain-token.sh;
-        source /polaris/obtain-token.sh;
-        echo Creating catalog...;
-        export STORAGE_CONFIG_INFO='{"storageType":"S3",
-          "endpoint":"http://localhost:9000",
-          "endpointInternal":"http://minio:9000",
-          "pathStyleAccess":true}';
-        export STORAGE_LOCATION='s3://warehouse';
-        /polaris/create-catalog.sh POLARIS $$TOKEN;
-        echo Extra grants...;
-        curl -H "Authorization: Bearer $$TOKEN" -H 'Content-Type: application/json' \
+        apk add --no-cache jq;
+        
+        echo "Obtaining access token...";
+        TOKEN=$$(curl -s http://polaris:8181/api/catalog/v1/oauth/tokens \
+          --user "$${CLIENT_ID}:$${CLIENT_SECRET}" \
+          -H "Polaris-Realm: POLARIS" \
+          -d grant_type=client_credentials \
+          -d scope=PRINCIPAL_ROLE:ALL | sed -n 's/.*"access_token":"\([^"]*\)".*/\1/p');
+        
+        if [ -z "$${TOKEN}" ]; then
+          echo "Failed to obtain access token.";
+          exit 1;
+        fi;
+        echo "Obtained access token";
+        
+        echo "Creating catalog...";
+        STORAGE_LOCATION="s3://warehouse";
+        STORAGE_CONFIG_INFO='{"storageType":"S3","endpoint":"http://localhost:9000","endpointInternal":"http://minio:9000","pathStyleAccess":true}';
+        
+        PAYLOAD="{
+          \"catalog\": {
+            \"name\": \"warehouse\",
+            \"type\": \"INTERNAL\",
+            \"readOnly\": false,
+            \"properties\": {
+              \"default-base-location\": \"$${STORAGE_LOCATION}\"
+            },
+            \"storageConfigInfo\": $${STORAGE_CONFIG_INFO}
+          }
+        }";
+        
+        echo "$${PAYLOAD}";
+        
+        curl -s -H "Authorization: Bearer $${TOKEN}" \
+          -H "Accept: application/json" \
+          -H "Content-Type: application/json" \
+          -H "Polaris-Realm: POLARIS" \
+          http://polaris:8181/api/management/v1/catalogs \
+          -d "$${PAYLOAD}" -v;
+        
+        echo "Extra grants...";
+        curl -H "Authorization: Bearer $${TOKEN}" -H "Content-Type: application/json" \
           -X PUT \
           http://polaris:8181/api/management/v1/catalogs/warehouse/catalog-roles/catalog_admin/grants \
           -d '{"type":"catalog", "privilege":"CATALOG_MANAGE_CONTENT"}';
-        echo Done.;
+        
+        echo "Done.";
+    networks:
+      - kafka-net
+
+  # ==========================================================
+  #  REDIS CACHE (Geo-enrichment address cache)
+  # ==========================================================
+  redis:
+    image: redis:7-alpine
+    container_name: redis
+    ports:
+      - "6379:6379"
+    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
+    volumes:
+      - redis-data:/data
+    networks:
+      - kafka-net
+    healthcheck:
+      test: ["CMD", "redis-cli", "ping"]
+      interval: 5s
+      timeout: 3s
+      retries: 5
+
+  redis-commander:
+    image: rediscommander/redis-commander:latest
+    container_name: redis-commander
+    environment:
+      REDIS_HOSTS: local:redis:6379
+    ports:
+      - "8083:8081"
+    depends_on:
+      redis:
+        condition: service_healthy
     networks:
       - kafka-net
 
@@ -359,3 +495,4 @@ volumes:
   minio-data:
   postgres-data:
   grafana-data:
+  redis-data:
